[[redirects]]
  from = "/*"
  to = "https://inkdao.tech/:splat"
  status = 301
  force = true
  conditions = { Host = ["decentralizedx.tech", "www.decentralizedx.tech"] }

[[redirects]]
from = "/*"
to = "/index.html"
status = 200